version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: sample-db-container
    ports:
      - 3306:3306 # host:container
    environment:
      LANG: C.UTF-8 # you can use some languages like Korean because of this setting
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "sample"
    command:
      - --character-set-server=utf8mb4 # set container character set
      - --collation-server=utf8mb4_unicode_ci # set container character set
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d # apply utf8 through the cnf file
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d # execute files after initializing the container