version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: sample-db-container
    ports:
      - 3306:3306
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "sample"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d