CREATE TABLE `BOARD`
(
    `BOARD_NO` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '게시글 번호',
    `CONTENT` MEDIUMTEXT COMMENT '내용',
    `REG_ID` VARCHAR(30) NOT NULL COMMENT '등록자 아이디',
    `REG_DT` DATETIME NOT NULL COMMENT '등록 시간',
    `UDT_ID` VARCHAR(30) COMMENT '수정자 아이디',
    `UDT_DT` DATETIME COMMENT '수정 시간',
    PRIMARY KEY ( `BOARD_NO` )
) ENGINE = InnoDB
 CHARACTER SET utf8
 COLLATE utf8_unicode_ci
 ROW_FORMAT = DYNAMIC
 COMMENT = '게시판';